package cz.dd4j.agents.heroes;

import java.util.List;
import java.util.Random;

import cz.dd4j.agents.HeroAgentBase;
import cz.dd4j.agents.commands.Command;
import cz.dd4j.simulation.data.dungeon.elements.entities.Hero;

/**
 * Fully-random-valid-action hero.
 * 
 * Chooses random action from the set of available actions as generated by {@link HeroAgentBase#actionsGenerator}.
 * 
 * @author Jimmy
 */
public class HeroRandom extends HeroAgentBase {

	private Random random;
	
	public HeroRandom() {
		random = new Random();
	}
	
	public HeroRandom(long seed) {
		random = new Random(seed);
	}
	
	@Override
	public Command act() {		
		List<Command> actions = actionsGenerator.generateFor(hero);
		if (actions.size() == 0) return null;
		Command selectedAction = actions.get(random.nextInt(actions.size()));
		return selectedAction;
	}

}
