package cz.dd4j.agents.heroes;

import cz.dd4j.agents.HeroAgentBase;
import cz.dd4j.agents.commands.Command;

/**
 * Fully-random-valid-action hero.
 * 
 * Chooses random action from the set of available actions as generated by {@link HeroAgentBase#actionsGenerator}.
 * 
 * @author Jimmy
 */
public class HeroRandom extends HeroAgentBase {

	@Override
	public Command act() {		
		return getRandomAction(hero, true);
	}

}
